// Microsoft .NET/.NET 8/ASP.NET/React Web Reporting Sample/Client/src/WebReportDesigner.tsx
﻿import { useExternalScript } from './hooks/useExternalScript';

export const WebReportDesigner = () => {
    const state = useExternalScript("https://localhost:7146/WebReportDesigner.js");

    return (
        <div>
            <div>
                <title>WebReportDesigner</title>
            </div>
            <div>
                {state === "loading" && <p>Loading...</p>}
                                                                                                                    {/*US: You can define the ClientData String and pass it to provideListLabelContext here*/}
                                                                                                                    {/*D:  Definition eines ClientData strings welcher an provideListLabelContext weitergegeben wird*/}
                {state === "ready" && <ll-webreportdesigner backendurl="https://localhost:7146/LLWebReportDesigner" showTutorial clientData="{'testdata':'Im a test object'}" />}
				
            </div>
        </div>
    );
}

// Microsoft .NET/.NET 8/ASP.NET/Vue Web Reporting Sample/Client/src/components/WebReportDesigner.vue
<template>
    <div>
                                                                                <!--US: You can define the ClientData String and pass it to provideListLabelContext here-->
                                                                                <!--D:  Definition eines ClientData strings welcher an provideListLabelContext weitergegeben wird-->
        <ll-webreportdesigner backendurl="https://localhost:5011/LLWebReportDesigner" showTutorial clientData="{'testdata':'Im a test object'}" />

    </div>
</template>

<script lang="ts">

</script>
