// Microsoft .NET/.NET 6/ASP.NET/React MVC Web Reporting Sample/client-app/src/WebReportDesigner.tsx
﻿import React from 'react';
import { useExternalScript } from './hooks/useExternalScript';

export const WebReportDesigner = () => {
    const state = useExternalScript("https://localhost:7260/WebReportDesigner.js");

    return (
        <div>
            <div>
                <title>WebReportDesigner</title>
            </div>
            <div>
                {state === "loading" && <p>Loading...</p>}
				
                {/* US: Comment this line in if you have set the example in file "DefaultSettings.cs" to English.*/}
				{state === "ready" && <ll-webreportdesigner backendurl="https://localhost:7260/LLWebReportDesigner" defaultProject="42B325E5-A894-4BDE-9D0A-5098B46A5085" />}
				
                {/* D: Kommentieren Sie diese Zeile ein, wenn Sie das Beispiel in Datei "DefaultSettings.cs" auf Deutsch gestellt haben.*/}
                {/* {state === "ready" && <ll-webreportdesigner backendurl="https://localhost:7260/LLWebReportDesigner" defaultProject="305D94C6-E5DC-4BE1-BC43-12CBC532EEE6" />}*/}
            </div>
        </div>
    );
}

// Microsoft .NET/.NET 6/ASP.NET/VueJS MVC Web Reporting Sample/VueJS MVC Web Reporting Sample/src/components/WebReportDesigner.vue
<template>
    <div>
        <!--US: Comment this line in if you have set the example in file "DefaultSettings.cs" to English.-->
        <ll-webreportdesigner backendurl="https://localhost:5011/LLWebReportDesigner" defaultProject="42B325E5-A894-4BDE-9D0A-5098B46A5085" />

        <!--D: Kommentieren Sie diese Zeile ein, wenn Sie das Beispiel in Datei "DefaultSettings.cs" auf Deutsch gestellt haben.-->
        <!--<ll-webreportdesigner backendurl="https://localhost:5011/LLWebReportDesigner" defaultProject="305D94C6-E5DC-4BE1-BC43-12CBC532EEE6" />-->
    </div>
</template>

<script lang="ts">

</script>
